webtalk_init -webtalk_dir D:/projects/arduissimo/release/v0.1/vivado/simulation_quad/simulation_quad.sim/sim_1/behav/xsim/xsim.dir/tb_quad_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Dec  3 18:42:50 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "bd6c3712-a1b1-4e4d-9899-011880762cac" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d6964b5d764f404483b60e27f1159462" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2012 R2 or Windows 8.1" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A10-6700 APU with Radeon(tm) HD Graphics   " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3691 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "957.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "18564_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3091338411 -regid "" -xml D:/projects/arduissimo/release/v0.1/vivado/simulation_quad/simulation_quad.sim/sim_1/behav/xsim/xsim.dir/tb_quad_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/projects/arduissimo/release/v0.1/vivado/simulation_quad/simulation_quad.sim/sim_1/behav/xsim/xsim.dir/tb_quad_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/projects/arduissimo/release/v0.1/vivado/simulation_quad/simulation_quad.sim/sim_1/behav/xsim/xsim.dir/tb_quad_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
