# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/sdp_ram_512x32x4/sdp_ram_512x32x4.xci
# IP: The module: 'sdp_ram_512x32x4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/sdp_ram_512x32x4/sdp_ram_512x32x4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdp_ram_512x32x4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/sdp_ram_512x32x4/sdp_ram_512x32x4.xci
# IP: The module: 'sdp_ram_512x32x4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/sdp_ram_512x32x4/sdp_ram_512x32x4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdp_ram_512x32x4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
