# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/tdp_ram_512x32/tdp_ram_512x32.xci
# IP: The module: 'tdp_ram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/tdp_ram_512x32/tdp_ram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdp_ram_512x32'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/tdp_ram_512x32/tdp_ram_512x32.xci
# IP: The module: 'tdp_ram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/projects/arduissimo/release/v0.1/vivado/fpga_top/fpga_top.srcs/sources_1/ip/tdp_ram_512x32/tdp_ram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tdp_ram_512x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
